### ISSUE TITLE
4Doc - Campylobacter spp. - JSON Representation (Franz BAG)

### ISSUE THREAD

**Issue by ig-feedback** [ahdis/ch-elm#100]
ch.fhir.ig.ch-elm#1.3.1 /Bundle-4Doc-Campylobacter.json.html

Der Titel dieses Beispieldokuments ändern.
Bisher: 4Doc Campylobacter spp.
Neu: 4Doc Campylobacter coli

Franz BAG

**Comment by oliveregger** [comment]
fixed with [1.4.0](../releases/tag/v1.4.0)
