### ISSUE TITLE
additionals examples for Neisseria meningitidis, Measles and Dengue and updated valuesets

### ISSUE THREAD

**Issue by oliveregger** [ahdis/ch-elm#111]

**Comment by oliveregger** [comment]
add name: 17Doc - Neisseria meningitidis – microscopic finding
description: Example Document for a microscopic observation of Neisseria meningitidis by primary lab

**Comment by oliveregger** [comment]
18Doc-C.diphtheriae      description: Example Document for Corynebacterium diphtheriae with specimen specification
19Doc-S.pneumoniae    description: Example Document for Streptococcus pneumoniae
20Doc-Vibrio cholerae  description: Example Document for Vibrio cholerae
21Doc-HepatiteE             description: Example Document for Hepatite E
22Doc-H.influenzae       description: Example Document for Haemophilus influenzae
23Doc-F.tularensis          description: Example Document for Francisella tularensis with organism specification

**Comment by SabrinaVivien** [comment]
Bundle-17Doc-Neisseria has still a error, it tries to find a valueset [ValueSet/ch-elm-results-men-org](https://ws.infreport-a.bag.admin.ch/ch-elm/v1/fhir/ValueSet/ch-elm-results-men-org) which is not yet available

**Comment by oliveregger** [comment]
fixed with [1.4.0](../releases/tag/v1.4.0)
