### ISSUE TITLE
discriminator type 'pattern' has been deprecated

### ISSUE THREAD

**Issue by ziegm** [ahdis/ch-elm#126]
Use type=value instead

Details see https://github.com/hl7ch/ch-core/issues/306

**Comment by ziegm** [comment]
It is caused by the parent profiles, so it can be suppressed ([suggestion from Grahame](https://chat.fhir.org/#narrow/channel/179252-IG-creation/topic/deprecated.20pattern.20slicing)) until it is fixed in the parent profiles.

**Comment by oliveregger** [comment]
fixed in 1.7.0
