### ISSUE TITLE
CH ELM Lab Specimen Types: Chlamydia Trachomatis (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ig-feedback** [ahdis/ch-elm#25]
ch.fhir.ig.ch-elm#1.0.0-trialuse /ValueSet-ch-elm-lab-specimen-types-chlamydia-trachomatis.html

Der Name/URL und allenfalls der Inhalt (?) muss angepasst werden, da das VS Werte von der Gruppe "geni-spec" enthält und nicht Erregerspezifisch ist.

Michaela Ziegler, ahdis ag

**Comment by ziegm** [comment]
Rücksprache mit BAG (Franz Auf der Maur):
- Inhalt bleibt der Gleiche im Moment
- Umbenennung zu http://fhir.ch/ig/ch-elm/ValueSet/ch-elm-results-geni-spec
