### ISSUE TITLE
CH ELM Lab Specimen Types (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ig-feedback** [ahdis/ch-elm#26]
ch.fhir.ig.ch-elm#1.0.0-ci-build /ValueSet-ch-elm-lab-specimen-types.html

Je nach ValueSet Mechanismus braucht es dieses VS nicht mehr.

Michaela Ziegler, ahdis ag

**Comment by ziegm** [comment]
Rücksprache mit BAG (Franz Auf der Maur):
- ValueSet entfernen, da es mit dem neuen Konzept der ConceptMaps und ValueSets bereits abgedeckt wird. Ist somit doppelt dokumentiert und eine allfällige Fehlerquelle, wenn dieses ValueSet im Update Zyklus vergessen ginge.
