### ISSUE TITLE
CH ELM Organization: Orderer - BUR und UID aktivieren (Franz BAG)

### ISSUE THREAD

**Issue by ig-feedback** [ahdis/ch-elm#52]
ch.fhir.ig.ch-elm#1.0.0 /StructureDefinition-ch-elm-organization-orderer.html

die auftraggebende Organisation muss künftig via BUR und/oder UID identifiziert werden. BUR und UID sollen Kardinalität 0..1 erhalten. GLN auf 0..1 belassen. Die ZSR brauchen wir nicht.

Franz BAG

**Comment by oliveregger** [comment]
Betrifft das nur die autraggebende Organisation
https://build.fhir.org/ig/ahdis/ch-elm/StructureDefinition-ch-elm-organization-orderer.html

Oder auch das Labor?
https://build.fhir.org/ig/ahdis/ch-elm/StructureDefinition-ch-elm-organization-lab.html

und/oder Broker/Author?
https://build.fhir.org/ig/ahdis/ch-elm/StructureDefinition-ch-elm-organization-author.html

In dem Fall müssen wir auch das logische Modell entsprechend adaptieren?
https://build.fhir.org/ig/ahdis/ch-elm/StructureDefinition-LaboratoryReport.html

**Comment by oliveregger** [comment]
fixed in 1.1.0
