### ISSUE TITLE
1bDoc - Neisseria Gonorrhoeae - JSON Representation (Oliver Egger, ahdis ag)

### ISSUE THREAD

**Issue by ig-feedback** [ahdis/ch-elm#55]
ch.fhir.ig.ch-elm#1.0.1 /Bundle-1bDoc-NeisseriaGonorrhoeae.json.html

Example has reference to Specimen/1Spec-Specimen which is not included in the bundle. Should those point to Specimen/1bSpec-Specimen?

Oliver Egger, ahdis ag

**Comment by oliveregger** [comment]
fixed in 1.1.0
