### ISSUE TITLE
Pat - Antoine Dupont - JSON Representation (Oliver Egger, ahdis ag)

### ISSUE THREAD

**Issue by ig-feedback** [ahdis/ch-elm#57]
ch.fhir.ig.ch-elm#1.0.0 /Patient-Pat-AntoineDupont.json.html

The examples should have the adress.line also specified (in this example: Rue de la république 18"), even the IG requires in addtiiton the extension streetLine and streetNumber.

Oliver Egger, ahdis ag

**Comment by oliveregger** [comment]
fixed in 1.1.0
