### ISSUE TITLE
fix ig dependencies to published versions

### ISSUE THREAD

**Issue by ziegm** [ahdis/ch-elm#6]
as soon as the igs where we are depending on are published, change the version to a fix one (not current):

-   ch.fhir.ig.ch-lab-report: current
    -   hl7.fhir.eu.laboratory: current 
-   ch.fhir.ig.ch-core: current

**Comment by oliveregger** [comment]
this can be adapted now to:

 hl7.fhir.eu.laboratory: 0.1.0-ballot
 ch.fhir.ig.ch-lab-report: 0.1.1
 ch.fhir.ig.ch-core: 4.0.1

**Comment by oliveregger** [comment]
fixed in 1.1.0
