### ISSUE TITLE
Different spelling of FOPH (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ziegm** [ahdis/ch-elm#63]
Unification of spelling for FOPH/Foph

![image](https://github.com/ahdis/ch-elm/assets/32767151/54150827-7639-4424-8b1f-f3c0dde6db72)

**Comment by ziegm** [comment]
it only concerns this line

https://github.com/ahdis/ch-elm/blob/bfd8b90667326f6f9cfdef400258b2da68f1ff12/input/resources/CodeSystem-ch-elm-foph-business-rules.json#L7

**Comment by oliveregger** [comment]
resolved with version 1.2.0
