### ISSUE TITLE
Reminder: update to the newest versions (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ziegm** [ahdis/ch-elm#65]
See also https://github.com/hl7ch/ch-lab-report/issues/52

16.02.2024: checked with the current builds of EU LAB and CH LAB-Report (and CH Core) -> no conflicts with EU LAB

**Comment by ziegm** [comment]
12.04.2024: to change with the newest version of CH LAB-Report
- Parent of ChElmCodeableConcept: CodeableConcept -> CodeableConceptIPS
- Parent of ChElmCoding: Coding -> CodingIPS
- Parent of ChElmSpecimen: ChLabReportSpecimen -> ChLabSpecimen

**Comment by oliveregger** [comment]
integrated with version 1.4.0

**Comment by oliveregger** [comment]
fixed with [1.4.0](../releases/tag/v1.4.0)
