### ISSUE TITLE
Validation via DocmentReference does not show enough details

### ISSUE THREAD

**Issue by oliveregger** [ahdis/ch-elm#68]
see https://github.com/ahdis/matchbox/issues/197

>If we test the ConceptMap CH ELM Expecting Specimen Specification To Results Completion Vs and intentionally send a specimen code that is not allowed per valueset ("geni_spec"), then the document is correctly rejected, but the error message is misleading ('Must have a resolvable URL conforming to the CH-ELM Bundle.') and says nothing about the actual problem why it is not conform.

the invariant itself is not sufficient to get the failing validation information and we should make it more explicit with introducing slice constraint:

1. https://fhir.ch/ig/ch-elm/StructureDefinition-PublishDocumentReference.html
add slice for min 1 contained resource Bundle with profile http://fhir.ch/ig/ch-elm/StructureDefinition/ch-elm-document
 
2. https://fhir.ch/ig/ch-elm/StructureDefinition-PublishDocumentReferenceStrict.html
constrain  slice above for min 1 contained resource Bundle with profile http://fhir.ch/ig/ch-elm/StructureDefinition/ch-elm-document-strict

we could simplify then also the constraint that is only checks that url resolves and remove the conformsTo

**Comment by ziegm** [comment]
Validation problems with the slicing occured: https://chat.fhir.org/#narrow/stream/179252-IG-creation/topic/Problem.20with.20slicing.20validation
