### ISSUE TITLE
Einbau ValueSet Specimen.type

### ISSUE THREAD

**Issue by oliveregger** [ahdis/ch-elm#72]
Für Specimen.type wird das BAG ein ValueSet zu Verfügung stellen

**Comment by ziegm** [comment]
see also #31

**Comment by ziegm** [comment]
Valueset für Gesamt-Material-Liste steht nun bereit: complete_spec

**Comment by oliveregger** [comment]
Das Valueset ist unter dem Endpunkt https://ws.infreport-a.bag.admin.ch/ch-elm/v1/fhir/ValueSet/ch-elm-results-complete-spec abrufbar.

Das Labor kann jederzeit (auch wenn die Specimen ConceptMap dies nicht verlangt) einen speciment.type.code melden. Wenn ein specimen.type.code angegeben ist, muss er aus dem definierten Gesamt-Material-Valueset stammen

**Comment by oliveregger** [comment]
resovled with version 1.2.0
