### ISSUE TITLE
Observation.value mandatory?

### ISSUE THREAD

**Issue by oliveregger** [ahdis/ch-elm#81]
Observation.value has in ch-elm-observation-results-laboratory-definition an min cardinality of 1

https://fhir.ch/ig/ch-elm/StructureDefinition-ch-elm-observation-results-laboratory-definitions.html#diff_Observation.value[x]

where does this rule come from?
I don't see it required by eu-lab: https://hl7.eu/fhir/laboratory/0.1.0-ballot/StructureDefinition-Observation-resultslab-eu-lab.html

**Comment by ziegm** [comment]
![image](https://github.com/ahdis/ch-elm/assets/32767151/1da14266-86ff-44e7-ab8d-f9bc1532309e)

from the logical model: https://fhir.ch/ig/ch-elm/StructureDefinition-LaboratoryReport.html

**Comment by oliveregger** [comment]
Diskussion vom 2.5, Entscheid BAG: wird aufgehoben um umgesetzt für Release 1.3.0
