### ISSUE TITLE
mal_Org im IG 1.3.1 mit nehmen

### ISSUE THREAD

**Issue by TOY-BAG** [ahdis/ch-elm#88]
Release 1.3.1 

Für der Release 1.3.1 sollten wir weitere punkt mit nehmen: 
- Erreger gruppe "mal_org" mitnehmen um die species für Malaria melden zu können. 
- 7 neue Snomed code für Legionella Spp. eintragen. (Konfiguration werden im DX gemacht werden). 
- Anpassungen für code "Hepatitis B virus core Ab [Presence] in Serum or Plasma by Immunoassay" um es melden zu können!

@oliveregger 

Stand 11.06.2024: 
- Erreger Gruppe "mal_org" und die 7 Snomed code für Legionella Spp. sind bereit für der Release 1.3.1. 
  Die Konfiguration unter DX wurde gemacht und sollte gehen!

**Comment by oliveregger** [comment]
@TOY-BAG den dritten Punkt (Anpassungen für code "Hepatitis B virus core Ab) sehe ich nicht im 
6c2a93d , ist das korrekt?

**Comment by TOY-BAG** [comment]
@oliveregger Ja richtig, wir sind nicht so weit bereit für diese Hepatitis B Code. Ich werde diese in der Nächste Release anpassen. (Erik muss noch etwas mit Marcel anschauen). 

Lg
Yannick

**Comment by oliveregger** [comment]
fixed in 1.3.1
