### ISSUE TITLE
CH ELM Patient - Entfernung der Verpflichtung für extension line (Oliver Egger, ahdis ag)

### ISSUE THREAD

**Issue by ig-feedback** [ahdis/ch-elm#91]
ch.fhir.ig.ch-elm#1.3.0 /StructureDefinition-ch-elm-patient.html

Entfernung der 1..* Requirement für extension in der Address.line
Meeting vom 10.6 mit FM, OE

Oliver Egger, ahdis ag

**Comment by oliveregger** [comment]
für 1.3.1

**Comment by oliveregger** [comment]
mustSupport von houseNummer rausnehmen

**Comment by oliveregger** [comment]
zusätzlich servicerquest.identifier.system rausnehmen da er in den beispiel immer auf einen pseudo value gesetzt wurde: 
http://fhir.lab.ch/order-identifier

**Comment by oliveregger** [comment]
fixed in version 1.3.1
