### ISSUE TITLE
DocumentReference for sending the report (meeting vom 17.6)

### ISSUE THREAD

**Issue by ig-feedback** [ahdis/ch-elm#97]
ch.fhir.ig.ch-elm#1.3.1 /StructureDefinition-PublishDocumentReference.html

"Must have a resolvable URL" can have a double meaning:

must resolve to the contained bundle

meeting vom 17.6

**Comment by oliveregger** [comment]
fixed with [1.4.0](../releases/tag/v1.4.0)
